# Generated by Django 4.2.6 on 2023-11-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_drone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "image",
                    models.CharField(
                        default="https://example.com/default-drone-image.png",
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
